version: 2.1

orbs:
  maven: circleci/maven@1.0.2
  codecov: codecov/codecov@1.0.2

workflows:
  maven_test:
    jobs:
      - maven/test:
        test_results_path: '/target/my-reports'
      - codecov/upload:
        file: { { target/my-reports } }
      